export const GET_LOCATIONS_START = 'GET_LOCATIONS_START';
export const GET_LOCATIONS_COMPLETE = 'GET_LOCATIONS_COMPLETE';
export const GET_LOCATIONS_ERROR = 'GET_LOCATIONS_ERROR';

export const GET_ROUTES_START = 'GET_ROUTES_START';
export const GET_ROUTES_ERROR = 'GET_ROUTES_ERROR';
export const GET_ROUTES_SUCCESS = 'GET_ROUTES_SUCCESS';
